name: translator
version: 0.0.1
description: A free Google Translate API for Dart
author: Gabriel N. Pacheco <gabrielpacheco23@live.com>
homepage: https://github.com/gabrielpacheco23/google-translator
dependencies:
  http: ^0.11.3+17

dev_dependencies:
  test: any

environment:
    sdk: ">=1.8.0 <2.0.0"